"""
Django settings for Aldempro project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import django_heroku


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from django.utils.translation import gettext_lazy as _


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-op)%sbz31qyw_$-s1fia=af(4ipl@vpjl+6-eo54vnt&v!qz10'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'markdownx',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Aldemapp',
    'crispy_forms',
    'crispy_bootstrap4',
    'django_select2',
    'widget_tweaks',
    'django_user_agents',
    'django.contrib.sitemaps',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # تأكد من وجود هذا السطر
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # 'Aldemapp.middleware.BlockChangeAfterFirstLoginMiddleware',
    


]
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000/','http://localhost:8000/','https://aldem-1d6e563a8a5f.herokuapp.com/','http://35.178.203.91']

SECURE_FRAME_DENY = True
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'Aldempro.urls'
WSGI_APPLICATION = 'Aldempro.wsgi.application'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Aldempro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'database-aldeme',  # The name of your database on AWS RDS
#         'USER': 'postgres',    # Your PostgreSQL username
#         'PASSWORD': 'L3tAqH4phzpJLA4uYbVR',  # Your PostgreSQL password
#         'HOST': 'database-aldeme.cts0gwgmadga.eu-west-2.rds.amazonaws.com',  # Your AWS RDS endpoint
#         'PORT': '5432',  # The default PostgreSQL port
#     },
#     # 'OPTIONS': {
#     # 'sslmode': 'require',
# # }
    
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuwait'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



STATIC_URL = '/static/'
#STATIC_ROOT = BASE_DIR / 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static/')
#STATICFILES_DIRS = [
#    BASE_DIR / "static",  # Assuming your static files are located in a 'static' directory at the project root
#]
#STATIC_ROOT = '/var/www/static'
# django_heroku.settings(locals())

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_TEMPLATE_PACK = 'bootstrap4'


LOGIN_REDIRECT_URL = 'student'
LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = '/'

LANGUAGES = [
    ('ar', _('Arabic')),
    # Add other languages here if needed
]

# Set the default language to Arabic
LANGUAGE_CODE = 'ar'

# Path to the locale directory
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


JAZZMIN_SETTINGS = {
    'welcome_sign': 'أهلاً وسهلاً في إدارة موقع الأستاذة الدمرداش',
    "site_title": "لوحة تحكم الدمرداش",
    "site_header": "لوحة تحكم الدمرداش", 
    "site_brand": "ALDEMRDASH",
    # 'show_sidebar': True,
    "login_logo":'assets/img/logo/logo.jpg',
    # 'show_ui_builder':True
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Replace with your preferred backend

EMAIL_PORT = 587  # Replace with your email port
EMAIL_USE_TLS = True  # Set to False if your email server doesn't use TLS
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your email host for gmail -> 'smtp.gmail.com'
EMAIL_HOST_USER = 'mtsmy31@gmail.com'  # Replace with your email username
EMAIL_HOST_PASSWORD = 'iqxc pbbq sxdr nzcs'  # Replace with your email password
DEFAULT_FROM_EMAIL = 'mtsmy31@gmail.com' 



SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # مدة الجلسة هي ساعة واحدة


# settings.py

DEVICE_COOKIE_NAME = 'device_id'
DEVICE_COOKIE_AGE = 365 * 24 * 60 * 60  # 1 year
DEVICE_COOKIE_DOMAIN = None  # Use default domain, or specify domain if needed
DEVICE_COOKIE_PATH = '/'
DEVICE_COOKIE_SECURE = True  # Set to True if using HTTPS
DEVICE_COOKIE_HTTPONLY = True
DEVICE_COOKIE_SAMESITE = 'Lax'  # Set to 'None', 'Lax', or 'Strict' based on your needs



X_FRAME_OPTIONS = 'SAMEORIGIN'

    
AWS_ACCESS_KEY_ID =  os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY =  os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'alldem'
AWS_S3_REGION_NAME = 'eu-west-2'  # e.g. 'us-east-1'

#AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_CUSTOM_DOMAIN = 'd2t7pfet7k6zuu.cloudfront.net'
# Set S3 as the default file storage
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Optional: Cache control and media root path
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=31536000',
}

MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'


# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:8000',
#     }
# }


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR,'media')
