# Generated by Django 5.0.6 on 2024-09-22 21:54
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0033_alter_subject_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('msg', models.TextField(verbose_name='رسالة الطالب')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('msg_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الرسالة')),
            ],
            options={
                'verbose_name': 'رسائل الطلاب',
                'verbose_name_plural': 'رسائل الطلاب',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم المادة')),
                ('url', models.CharField(max_length=250, verbose_name='رابط قائمة التشغيل')),
                ('type', models.CharField(choices=[('math', 'رياضيات'), ('counting', 'إحصاء'), ('phsic', 'فيزياء'), ('cimstry', 'كيمياء'), ('economy', 'إقتصاد'), ('etc', 'أخرى')], default='', max_length=20, verbose_name='قسم المادة')),
            ],
            options={
                'verbose_name': 'المحاضرات التجريبية',
                'verbose_name_plural': 'المحاضرات التجريبية',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معرف المستخدم',
                'verbose_name_plural': 'معرفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الفيديو')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='غلاف المقطع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفيديو')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auth.subject')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'فيديوهات',
            },
        ),
    ]
