# Generated by Django 5.0.6 on 2024-10-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/', verbose_name='الفيديو'),
        ),
    ]
