# Generated by Django 5.0.6 on 2024-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='thumbnails/', verbose_name='غلاف المقطع'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(blank=True, max_length=355, null=True, upload_to='videos/', verbose_name='الفيديو'),
        ),
    ]
