# Generated by Django 5.0.6 on 2024-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0002_alter_videos_thumbnail_alter_videos_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['order'], 'verbose_name': 'فيديو', 'verbose_name_plural': 'فيديوهات'},
        ),
        migrations.AddField(
            model_name='videos',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب الفيديو'),
        ),
    ]
