# Generated by Django 5.0.6 on 2024-11-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0003_alter_videos_options_videos_order'),
        ('Aldemapp', '0003_alter_videos_options_videos_order_and_more'),
    ]

    operations = [
    ]
