# Generated by Django 5.0.6 on 2024-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='method',
            field=models.CharField(choices=[('email', 'Send via Email'), ('site', 'Send via Site')], default='site', max_length=10),
        ),
    ]
