# Generated by Django 5.0.6 on 2025-01-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldemapp', '0007_alter_notification_method'),
        ('auth', '0037_chapter_user_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='chapter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='auth.chapter'),
        ),
    ]
